# Generated by Django 2.1.2 on 2018-10-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20181012_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='ledger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('file_name', models.CharField(max_length=50)),
                ('file_extension', models.CharField(max_length=50)),
                ('file_type', models.CharField(max_length=50)),
                ('file_hash', models.CharField(max_length=150)),
                ('url', models.CharField(max_length=150)),
                ('file_status', models.BooleanField()),
                ('pin_status', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
